### ISSUE TITLE
Add server skeleton

### ISSUE THREAD

**Issue by claytondus** [claytondus/cdnwsh#2]

**Comment by nwilder0** [comment]
what does this include?

**Comment by claytondus** [comment]
Basically server.c, the server process.  I guess from the spec they don't necessarily intend to have two binaries (server and client), but just to start the client in server mode so it can be connected over the socket.  My thinking was to have a server and client, and the client always connects over the socket (IP or pipe).  What do you think?

**Comment by nwilder0** [comment]
yeah, I was thinking of having a separate client binary, but also including and troubleshooting the client functionality in the same binary as the shell and server.  Then to build a separate client binary, we would just need to have a simple main_client.c file that includes the same client.c and client.h as the main program and in main() just make a call to the remote shell function in client.c

I'm assuming also that the server will just be a normal running shell, and not a daemon like process; and that we will have just one server/shell running per machine at any given time.  This way we can statically define the tcp port.  Or we can get the tcp port dynamically on startup (by checking which are in use) and report it in stdout in order to know which port to use to connect remotely.

**Comment by claytondus** [comment]
I suppose that makes debugging easier for the server.  Static port sounds fine, no reason to run more than one at a time.
